steps:
    # Build the Docker image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/pro-talon-403817/gameofdrones-main", "."]

    # Run tests
    - name: "gcr.io/pro-talon-403817/gameofdrones-main"
      entrypoint: "npm"
      args: ["test"]

    # Push the image to Google Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/pro-talon-403817/gameofdrones-main"]

    # Deploy to Google Cloud Run
    - name: "gcr.io/cloud-builders/gcloud"
      args:
          [
              "run",
              "deploy",
              "g-of-d-run",
              "--image",
              "gcr.io/pro-talon-403817/gameofdrones-main",
              "--platform",
              "managed",
          ]
