FROM node:18

ARG CLOUD_DATABASE_HOST
ARG CLOUD_DATABASE_USER
ARG CLOUD_DATABASE_PASS
ARG CLOUD_DATABASE_NAME
ARG JWT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_COMMON_USER_PASSWORD

ENV CLOUD_DATABASE_HOST=$CLOUD_DATABASE_HOST
ENV CLOUD_DATABASE_USER=$CLOUD_DATABASE_USER
ENV CLOUD_DATABASE_PASS=$CLOUD_DATABASE_PASS
ENV CLOUD_DATABASE_NAME=$CLOUD_DATABASE_NAME
ENV JWT_SECRET=$JWT_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_COMMON_USER_PASSWORD=$GOOGLE_COMMON_USER_PASSWORD

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "npm", "run", "start:prod" ]