FROM node:18

ARG CLOUD_DATABASE_HOST
ARG CLOUD_DATABASE_USER
ARG CLOUD_DATABASE_PASS
ARG CLOUD_DATABASE_NAME
ARG JWT_SECRET
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_CALLBACK_URL
ARG FACEBOOK_APP_ID
ARG FACEBOOK_APP_SECRET
ARG FACEBOOK_CALLBACK_URL
ARG GOOGLE_COMMON_USER_PASSWORD
ARG REDIRECT_URL
ARG GOOGLE_MAIL_SENDER
ARG GOOGLE_MAIL_SENDER_PASS


ENV CLOUD_DATABASE_HOST=$CLOUD_DATABASE_HOST
ENV CLOUD_DATABASE_USER=$CLOUD_DATABASE_USER
ENV CLOUD_DATABASE_PASS=$CLOUD_DATABASE_PASS
ENV CLOUD_DATABASE_NAME=$CLOUD_DATABASE_NAME
ENV JWT_SECRET=$JWT_SECRET
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV GOOGLE_CALLBACK_URL=$GOOGLE_CALLBACK_URL
ENV FACEBOOK_APP_ID=$FACEBOOK_APP_ID
ENV FACEBOOK_APP_SECRET=$FACEBOOK_APP_SECRET
ENV FACEBOOK_CALLBACK_URL=$FACEBOOK_CALLBACK_URL
ENV REDIRECT_URL=$REDIRECT_URL
ENV GOOGLE_COMMON_USER_PASSWORD=$GOOGLE_COMMON_USER_PASSWORD
ENV GOOGLE_MAIL_SENDER=$GOOGLE_MAIL_SENDER
ENV GOOGLE_MAIL_SENDER_PASS=$GOOGLE_MAIL_SENDER_PASS

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD [ "npm", "run", "start:prod" ]
